### ISSUE TITLE
Inspection on generic type parameters

### ISSUE THREAD

**Issue by Muyangmin** [shiraji/create-intent-inspection#7]
Hello, I'm using the createIntent inspection plugin, it's really nice!
But, accidentally, today when I wrote the 

``` java
    public <T extends Activity> void method(T activity){

    } 
```

Then the plugins prompt the inspection of the T type, but this is only a _TYPE_ instead of _class_, so maybe this is a bug?

**Comment by shiraji** [comment]
Wow, I reproduced this issue. Thanks for reporting this. I will fix this problem as soon as possible.

**Comment by shiraji** [comment]
Implemented. 

I put jar [here](https://github.com/shiraji/create-intent-inspection/releases/tag/v0.0.2) in case you want to try it.
I will update this plugin soon, it will take a few days in public.

Thanks for using this plugin and reporting a problem!

**Comment by Muyangmin** [comment]
Thanks for your work!
