### ISSUE TITLE
Don't check for a constant method name while doing the inspection.

### ISSUE THREAD

**Issue by Avinash-Bhat** [shiraji/create-intent-inspection#9]
The method naming should be decided by the user of the plugin. For e.g., some like to create the factory method with name `newIntent()` while other may prefer something. This should be essentially configurable.

**Comment by shiraji** [comment]
Thanks for reporting. Since my projects always use `createIntent` and no one asked me to provide the configuration, I was too lazy to implement the function. 

I will work on that in next version.

**Comment by shiraji** [comment]
Implemented. Will be release next version of this plugin. Thanks.

**Comment by shiraji** [comment]
You can test it now [here](https://github.com/shiraji/create-intent-inspection/releases/download/v0.1.0/create-intent-inspection.jar) or wait until I will upload the module to plugin repo
